---
- name: Installing JAVA rpm 
  yum: name=java-1.8.0-openjdk state=present

- name: Installing Dependencies 
  yum: name=redhat-lsb-core state=present

- name: Download the kafka URL 
  get_url: url=http://www-eu.apache.org/dist/kafka/0.10.2.1/kafka_2.10-0.10.2.1.tgz dest=/kafka validate_certs=False

- name: Creating user kafka
  user: name=kafka state=present 

- name: UnArchive the kafka tarball 
  unarchive: src=/kafka/kafka_2.10-0.10.2.1.tgz dest=/kafka remote_src=True

- name: Rename kafka directory
  command: mv /kafka/kafka_2.10-0.10.2.1 /kafka/kafka

- name: Placing myid file 
  template: src=myid.j2 dest={{ zk_log_dir }}/myid owner=root group=root mode=0755

- name: Putting the service file for zookeeper
  template: src=zookeeper.j2 dest=/etc/init.d/zookeeper owner=root group=root mode=0755

- name: Putting zookeeper config file 
  template: src=zookeeper.properties.j2 dest=/kafka/kafka/config/zookeeper.properties owner=kafka group=kafka mode=0644
  notify:
    - "zookeeper start"

- name: Putting the service file for kafka
  template: src=kafka.j2 dest=/etc/init.d/kafka owner=root group=root mode=0755

- name: Putting kafka config file 
  template: src=server.properties.j2 dest=/kafka/kafka/config/server.properties owner=kafka group=kafka mode=0644
  notify:
    - "kafka start"


