---
- name: Install zabbix agent repo
  shell: rpm -ivh http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-release-3.0-1.el6.noarch.rpm 

- name: Install zabbix 
  yum: name=zabbix state=present

- name: Install zabbix
  yum: name=zabbix-agent state=present

- name: zabbix conf
  template: src=zabbix_agent.conf.j2 dest=/etc/zabbix/zabbix_agent.conf

- name: zabbix Kafka status conf
  copy: src=kafka_status.conf dest=/etc/zabbix/zabbix_agentd.d/kafka_status.conf owner=zabbix group=zabbix mode=0755

- name: zabbix Kafka lag conf
  template: src=kafka_lag.conf.j2 dest=/etc/zabbix/zabbix_agentd.d/kafka_lag.conf owner=zabbix group=zabbix mode=0755

- name: Zabbix Zookeeper conf
  copy: src=zookeeper_status.conf dest=/etc/zabbix/zabbix_agentd.d/zookeeper_status.conf owner=zabbix group=zabbix mode=0664
  notify:
    - "restart zabbix-agent"
